INC_DIR = include
SRC_DIR = src
OBJ_DIR = build
OBJSLIB = $(OBJ_DIR)/test_213inplace.o\
		$(OBJ_DIR)/transpose.o\
		$(OBJ_DIR)/introspect.o\
		$(OBJ_DIR)/rotate.o\
		$(OBJ_DIR)/permute.o\
		$(OBJ_DIR)/shuffle.o\
		$(OBJ_DIR)/col_shuffle.o\
		$(OBJ_DIR)/skinny.o\
		$(OBJ_DIR)/memory_ops.o\
		$(OBJ_DIR)/smem_ops.o\
		$(OBJ_DIR)/save_array.o\
		$(OBJ_DIR)/gcd.o\
		$(OBJ_DIR)/reduced_math.o\
		$(OBJ_DIR)/cudacheck.o\
		$(OBJ_DIR)/tensor_util.o\
        $(OBJ_DIR)/util.o\

OBJSGEN = $(OBJ_DIR)/gen_ans.o \
		$(OBJ_DIR)/tensor_util.o

OBJSCUTT = $(OBJ_DIR)/test_cutt.o \
		$(OBJ_DIR)/tensor_util.o \
		$(OBJ_DIR)/cudacheck.o \
		../cutt/lib/libcutt.a

CC = g++
NVCC = nvcc
CPPFLAGS = -I$(INC_DIR) -std=c++14 -O3
NVCCFLAGS = -arch=sm_61 -rdc=true

EXEC = test_213inplace gen_ans test_cutt
all: mkdir test_213inplace

mkdir:
	mkdir -p $(OBJ_DIR)

test_213inplace: $(OBJSLIB)
	$(NVCC) $(NVCCFLAGS) -o $@ $^
	
gen_ans: $(OBJSGEN)
	$(CC) $(CPPFLAGS) -o $@ $^

test_cutt: $(OBJSCUTT)
	$(NVCC) $(NVCCFLAGS) -L../cutt/lib -lcutt -o $@ $^
	
$(OBJ_DIR)/%.o : $(SRC_DIR)/%.cu $(OBJ_DIR)/%.d
	$(NVCC) -c $(CPPFLAGS) $(NVCCFLAGS) -o $@ $<

$(OBJ_DIR)/%.o : $(SRC_DIR)/%.cpp $(OBJ_DIR)/%.d
	$(CC) -c $(CPPFLAGS) -o $@ $<
	
$(OBJ_DIR)/%.d: $(SRC_DIR)/%.cu
	@echo "$(NVCC) -MM $(CPPFLAGS) $(NVCCFLAGS) $< > $@"
	@$(NVCC) -MM $(CPPFLAGS) $(NVCCFLAGS) $< > $@.tmp
	@sed 's,\($*\)\.o[ :]*,\1.o $@ : ,g' < $@.tmp > $@
	@rm -f $@.tmp

$(OBJ_DIR)/%.d: $(SRC_DIR)/%.cpp
	@echo "$(CC) -MM $(CPPFLAGS) $< > $@"
	@$(CC) -MM $(CPPFLAGS) $< > $@.tmp
	@sed 's,\($*\)\.o[ :]*,\1.o $@ : ,g' < $@.tmp > $@
	@rm -f $@.tmp
	
-include $(OBJSLIB:.o=.d)
	
clean:
	rm -f $(OBJ_DIR)/* $(EXEC)
